//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UngDungDesktop.QuanLiThuChiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuanLiThuChiService.XuLiDichVuSoap")]
    public interface XuLiDichVuSoap {
        
        // CODEGEN: Generating message contract since element name layDanhSachThanhVienResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/layDanhSachThanhVien", ReplyAction="*")]
        UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienResponse layDanhSachThanhVien(UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/layDanhSachThanhVien", ReplyAction="*")]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienResponse> layDanhSachThanhVienAsync(UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienRequest request);
        
        // CODEGEN: Generating message contract since element name chuoiDuLieuThuChi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/themKhoanThuChi", ReplyAction="*")]
        UngDungDesktop.QuanLiThuChiService.themKhoanThuChiResponse themKhoanThuChi(UngDungDesktop.QuanLiThuChiService.themKhoanThuChiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/themKhoanThuChi", ReplyAction="*")]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.themKhoanThuChiResponse> themKhoanThuChiAsync(UngDungDesktop.QuanLiThuChiService.themKhoanThuChiRequest request);
        
        // CODEGEN: Generating message contract since element name thongKeTheoNamResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/thongKeTheoNam", ReplyAction="*")]
        UngDungDesktop.QuanLiThuChiService.thongKeTheoNamResponse thongKeTheoNam(UngDungDesktop.QuanLiThuChiService.thongKeTheoNamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/thongKeTheoNam", ReplyAction="*")]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.thongKeTheoNamResponse> thongKeTheoNamAsync(UngDungDesktop.QuanLiThuChiService.thongKeTheoNamRequest request);
        
        // CODEGEN: Generating message contract since element name nam from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/thongKeTheoThang", ReplyAction="*")]
        UngDungDesktop.QuanLiThuChiService.thongKeTheoThangResponse thongKeTheoThang(UngDungDesktop.QuanLiThuChiService.thongKeTheoThangRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/thongKeTheoThang", ReplyAction="*")]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.thongKeTheoThangResponse> thongKeTheoThangAsync(UngDungDesktop.QuanLiThuChiService.thongKeTheoThangRequest request);
        
        // CODEGEN: Generating message contract since element name nam from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/thongKeThanhVienTheoNam", ReplyAction="*")]
        UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamResponse thongKeThanhVienTheoNam(UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/thongKeThanhVienTheoNam", ReplyAction="*")]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamResponse> thongKeThanhVienTheoNamAsync(UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamRequest request);
        
        // CODEGEN: Generating message contract since element name nam from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/thongKeThanhVienTheoThang", ReplyAction="*")]
        UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangResponse thongKeThanhVienTheoThang(UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/thongKeThanhVienTheoThang", ReplyAction="*")]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangResponse> thongKeThanhVienTheoThangAsync(UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangRequest request);
        
        // CODEGEN: Generating message contract since element name chuoiXmlDuLieuTimKiem from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/timKiem", ReplyAction="*")]
        UngDungDesktop.QuanLiThuChiService.timKiemResponse timKiem(UngDungDesktop.QuanLiThuChiService.timKiemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/timKiem", ReplyAction="*")]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.timKiemResponse> timKiemAsync(UngDungDesktop.QuanLiThuChiService.timKiemRequest request);
        
        // CODEGEN: Generating message contract since element name layIdThuChiChungResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/layIdThuChiChung", ReplyAction="*")]
        UngDungDesktop.QuanLiThuChiService.layIdThuChiChungResponse layIdThuChiChung(UngDungDesktop.QuanLiThuChiService.layIdThuChiChungRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/layIdThuChiChung", ReplyAction="*")]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.layIdThuChiChungResponse> layIdThuChiChungAsync(UngDungDesktop.QuanLiThuChiService.layIdThuChiChungRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class layDanhSachThanhVienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="layDanhSachThanhVien", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienRequestBody Body;
        
        public layDanhSachThanhVienRequest() {
        }
        
        public layDanhSachThanhVienRequest(UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class layDanhSachThanhVienRequestBody {
        
        public layDanhSachThanhVienRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class layDanhSachThanhVienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="layDanhSachThanhVienResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienResponseBody Body;
        
        public layDanhSachThanhVienResponse() {
        }
        
        public layDanhSachThanhVienResponse(UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class layDanhSachThanhVienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string layDanhSachThanhVienResult;
        
        public layDanhSachThanhVienResponseBody() {
        }
        
        public layDanhSachThanhVienResponseBody(string layDanhSachThanhVienResult) {
            this.layDanhSachThanhVienResult = layDanhSachThanhVienResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class themKhoanThuChiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="themKhoanThuChi", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.themKhoanThuChiRequestBody Body;
        
        public themKhoanThuChiRequest() {
        }
        
        public themKhoanThuChiRequest(UngDungDesktop.QuanLiThuChiService.themKhoanThuChiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class themKhoanThuChiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string chuoiDuLieuThuChi;
        
        public themKhoanThuChiRequestBody() {
        }
        
        public themKhoanThuChiRequestBody(string chuoiDuLieuThuChi) {
            this.chuoiDuLieuThuChi = chuoiDuLieuThuChi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class themKhoanThuChiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="themKhoanThuChiResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.themKhoanThuChiResponseBody Body;
        
        public themKhoanThuChiResponse() {
        }
        
        public themKhoanThuChiResponse(UngDungDesktop.QuanLiThuChiService.themKhoanThuChiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class themKhoanThuChiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string themKhoanThuChiResult;
        
        public themKhoanThuChiResponseBody() {
        }
        
        public themKhoanThuChiResponseBody(string themKhoanThuChiResult) {
            this.themKhoanThuChiResult = themKhoanThuChiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class thongKeTheoNamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="thongKeTheoNam", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.thongKeTheoNamRequestBody Body;
        
        public thongKeTheoNamRequest() {
        }
        
        public thongKeTheoNamRequest(UngDungDesktop.QuanLiThuChiService.thongKeTheoNamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class thongKeTheoNamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int offset;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int limit;
        
        public thongKeTheoNamRequestBody() {
        }
        
        public thongKeTheoNamRequestBody(int offset, int limit) {
            this.offset = offset;
            this.limit = limit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class thongKeTheoNamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="thongKeTheoNamResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.thongKeTheoNamResponseBody Body;
        
        public thongKeTheoNamResponse() {
        }
        
        public thongKeTheoNamResponse(UngDungDesktop.QuanLiThuChiService.thongKeTheoNamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class thongKeTheoNamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string thongKeTheoNamResult;
        
        public thongKeTheoNamResponseBody() {
        }
        
        public thongKeTheoNamResponseBody(string thongKeTheoNamResult) {
            this.thongKeTheoNamResult = thongKeTheoNamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class thongKeTheoThangRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="thongKeTheoThang", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.thongKeTheoThangRequestBody Body;
        
        public thongKeTheoThangRequest() {
        }
        
        public thongKeTheoThangRequest(UngDungDesktop.QuanLiThuChiService.thongKeTheoThangRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class thongKeTheoThangRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nam;
        
        public thongKeTheoThangRequestBody() {
        }
        
        public thongKeTheoThangRequestBody(string nam) {
            this.nam = nam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class thongKeTheoThangResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="thongKeTheoThangResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.thongKeTheoThangResponseBody Body;
        
        public thongKeTheoThangResponse() {
        }
        
        public thongKeTheoThangResponse(UngDungDesktop.QuanLiThuChiService.thongKeTheoThangResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class thongKeTheoThangResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string thongKeTheoThangResult;
        
        public thongKeTheoThangResponseBody() {
        }
        
        public thongKeTheoThangResponseBody(string thongKeTheoThangResult) {
            this.thongKeTheoThangResult = thongKeTheoThangResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class thongKeThanhVienTheoNamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="thongKeThanhVienTheoNam", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamRequestBody Body;
        
        public thongKeThanhVienTheoNamRequest() {
        }
        
        public thongKeThanhVienTheoNamRequest(UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class thongKeThanhVienTheoNamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nam;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idGiaDinh;
        
        public thongKeThanhVienTheoNamRequestBody() {
        }
        
        public thongKeThanhVienTheoNamRequestBody(string nam, int idGiaDinh) {
            this.nam = nam;
            this.idGiaDinh = idGiaDinh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class thongKeThanhVienTheoNamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="thongKeThanhVienTheoNamResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamResponseBody Body;
        
        public thongKeThanhVienTheoNamResponse() {
        }
        
        public thongKeThanhVienTheoNamResponse(UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class thongKeThanhVienTheoNamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string thongKeThanhVienTheoNamResult;
        
        public thongKeThanhVienTheoNamResponseBody() {
        }
        
        public thongKeThanhVienTheoNamResponseBody(string thongKeThanhVienTheoNamResult) {
            this.thongKeThanhVienTheoNamResult = thongKeThanhVienTheoNamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class thongKeThanhVienTheoThangRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="thongKeThanhVienTheoThang", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangRequestBody Body;
        
        public thongKeThanhVienTheoThangRequest() {
        }
        
        public thongKeThanhVienTheoThangRequest(UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class thongKeThanhVienTheoThangRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string thang;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idGiaDinh;
        
        public thongKeThanhVienTheoThangRequestBody() {
        }
        
        public thongKeThanhVienTheoThangRequestBody(string nam, string thang, int idGiaDinh) {
            this.nam = nam;
            this.thang = thang;
            this.idGiaDinh = idGiaDinh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class thongKeThanhVienTheoThangResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="thongKeThanhVienTheoThangResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangResponseBody Body;
        
        public thongKeThanhVienTheoThangResponse() {
        }
        
        public thongKeThanhVienTheoThangResponse(UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class thongKeThanhVienTheoThangResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string thongKeThanhVienTheoThangResult;
        
        public thongKeThanhVienTheoThangResponseBody() {
        }
        
        public thongKeThanhVienTheoThangResponseBody(string thongKeThanhVienTheoThangResult) {
            this.thongKeThanhVienTheoThangResult = thongKeThanhVienTheoThangResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class timKiemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="timKiem", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.timKiemRequestBody Body;
        
        public timKiemRequest() {
        }
        
        public timKiemRequest(UngDungDesktop.QuanLiThuChiService.timKiemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class timKiemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string chuoiXmlDuLieuTimKiem;
        
        public timKiemRequestBody() {
        }
        
        public timKiemRequestBody(string chuoiXmlDuLieuTimKiem) {
            this.chuoiXmlDuLieuTimKiem = chuoiXmlDuLieuTimKiem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class timKiemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="timKiemResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.timKiemResponseBody Body;
        
        public timKiemResponse() {
        }
        
        public timKiemResponse(UngDungDesktop.QuanLiThuChiService.timKiemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class timKiemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string timKiemResult;
        
        public timKiemResponseBody() {
        }
        
        public timKiemResponseBody(string timKiemResult) {
            this.timKiemResult = timKiemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class layIdThuChiChungRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="layIdThuChiChung", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.layIdThuChiChungRequestBody Body;
        
        public layIdThuChiChungRequest() {
        }
        
        public layIdThuChiChungRequest(UngDungDesktop.QuanLiThuChiService.layIdThuChiChungRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class layIdThuChiChungRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idGiaDinh;
        
        public layIdThuChiChungRequestBody() {
        }
        
        public layIdThuChiChungRequestBody(int idGiaDinh) {
            this.idGiaDinh = idGiaDinh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class layIdThuChiChungResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="layIdThuChiChungResponse", Namespace="http://tempuri.org/", Order=0)]
        public UngDungDesktop.QuanLiThuChiService.layIdThuChiChungResponseBody Body;
        
        public layIdThuChiChungResponse() {
        }
        
        public layIdThuChiChungResponse(UngDungDesktop.QuanLiThuChiService.layIdThuChiChungResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class layIdThuChiChungResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string layIdThuChiChungResult;
        
        public layIdThuChiChungResponseBody() {
        }
        
        public layIdThuChiChungResponseBody(string layIdThuChiChungResult) {
            this.layIdThuChiChungResult = layIdThuChiChungResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XuLiDichVuSoapChannel : UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XuLiDichVuSoapClient : System.ServiceModel.ClientBase<UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap>, UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap {
        
        public XuLiDichVuSoapClient() {
        }
        
        public XuLiDichVuSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XuLiDichVuSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XuLiDichVuSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XuLiDichVuSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienResponse UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.layDanhSachThanhVien(UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienRequest request) {
            return base.Channel.layDanhSachThanhVien(request);
        }
        
        public string layDanhSachThanhVien() {
            UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienRequest inValue = new UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienRequestBody();
            UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienResponse retVal = ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).layDanhSachThanhVien(inValue);
            return retVal.Body.layDanhSachThanhVienResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienResponse> UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.layDanhSachThanhVienAsync(UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienRequest request) {
            return base.Channel.layDanhSachThanhVienAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienResponse> layDanhSachThanhVienAsync() {
            UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienRequest inValue = new UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.layDanhSachThanhVienRequestBody();
            return ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).layDanhSachThanhVienAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngDungDesktop.QuanLiThuChiService.themKhoanThuChiResponse UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.themKhoanThuChi(UngDungDesktop.QuanLiThuChiService.themKhoanThuChiRequest request) {
            return base.Channel.themKhoanThuChi(request);
        }
        
        public string themKhoanThuChi(string chuoiDuLieuThuChi) {
            UngDungDesktop.QuanLiThuChiService.themKhoanThuChiRequest inValue = new UngDungDesktop.QuanLiThuChiService.themKhoanThuChiRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.themKhoanThuChiRequestBody();
            inValue.Body.chuoiDuLieuThuChi = chuoiDuLieuThuChi;
            UngDungDesktop.QuanLiThuChiService.themKhoanThuChiResponse retVal = ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).themKhoanThuChi(inValue);
            return retVal.Body.themKhoanThuChiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.themKhoanThuChiResponse> UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.themKhoanThuChiAsync(UngDungDesktop.QuanLiThuChiService.themKhoanThuChiRequest request) {
            return base.Channel.themKhoanThuChiAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.themKhoanThuChiResponse> themKhoanThuChiAsync(string chuoiDuLieuThuChi) {
            UngDungDesktop.QuanLiThuChiService.themKhoanThuChiRequest inValue = new UngDungDesktop.QuanLiThuChiService.themKhoanThuChiRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.themKhoanThuChiRequestBody();
            inValue.Body.chuoiDuLieuThuChi = chuoiDuLieuThuChi;
            return ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).themKhoanThuChiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngDungDesktop.QuanLiThuChiService.thongKeTheoNamResponse UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.thongKeTheoNam(UngDungDesktop.QuanLiThuChiService.thongKeTheoNamRequest request) {
            return base.Channel.thongKeTheoNam(request);
        }
        
        public string thongKeTheoNam(int offset, int limit) {
            UngDungDesktop.QuanLiThuChiService.thongKeTheoNamRequest inValue = new UngDungDesktop.QuanLiThuChiService.thongKeTheoNamRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.thongKeTheoNamRequestBody();
            inValue.Body.offset = offset;
            inValue.Body.limit = limit;
            UngDungDesktop.QuanLiThuChiService.thongKeTheoNamResponse retVal = ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).thongKeTheoNam(inValue);
            return retVal.Body.thongKeTheoNamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.thongKeTheoNamResponse> UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.thongKeTheoNamAsync(UngDungDesktop.QuanLiThuChiService.thongKeTheoNamRequest request) {
            return base.Channel.thongKeTheoNamAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.thongKeTheoNamResponse> thongKeTheoNamAsync(int offset, int limit) {
            UngDungDesktop.QuanLiThuChiService.thongKeTheoNamRequest inValue = new UngDungDesktop.QuanLiThuChiService.thongKeTheoNamRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.thongKeTheoNamRequestBody();
            inValue.Body.offset = offset;
            inValue.Body.limit = limit;
            return ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).thongKeTheoNamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngDungDesktop.QuanLiThuChiService.thongKeTheoThangResponse UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.thongKeTheoThang(UngDungDesktop.QuanLiThuChiService.thongKeTheoThangRequest request) {
            return base.Channel.thongKeTheoThang(request);
        }
        
        public string thongKeTheoThang(string nam) {
            UngDungDesktop.QuanLiThuChiService.thongKeTheoThangRequest inValue = new UngDungDesktop.QuanLiThuChiService.thongKeTheoThangRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.thongKeTheoThangRequestBody();
            inValue.Body.nam = nam;
            UngDungDesktop.QuanLiThuChiService.thongKeTheoThangResponse retVal = ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).thongKeTheoThang(inValue);
            return retVal.Body.thongKeTheoThangResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.thongKeTheoThangResponse> UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.thongKeTheoThangAsync(UngDungDesktop.QuanLiThuChiService.thongKeTheoThangRequest request) {
            return base.Channel.thongKeTheoThangAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.thongKeTheoThangResponse> thongKeTheoThangAsync(string nam) {
            UngDungDesktop.QuanLiThuChiService.thongKeTheoThangRequest inValue = new UngDungDesktop.QuanLiThuChiService.thongKeTheoThangRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.thongKeTheoThangRequestBody();
            inValue.Body.nam = nam;
            return ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).thongKeTheoThangAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamResponse UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.thongKeThanhVienTheoNam(UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamRequest request) {
            return base.Channel.thongKeThanhVienTheoNam(request);
        }
        
        public string thongKeThanhVienTheoNam(string nam, int idGiaDinh) {
            UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamRequest inValue = new UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamRequestBody();
            inValue.Body.nam = nam;
            inValue.Body.idGiaDinh = idGiaDinh;
            UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamResponse retVal = ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).thongKeThanhVienTheoNam(inValue);
            return retVal.Body.thongKeThanhVienTheoNamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamResponse> UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.thongKeThanhVienTheoNamAsync(UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamRequest request) {
            return base.Channel.thongKeThanhVienTheoNamAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamResponse> thongKeThanhVienTheoNamAsync(string nam, int idGiaDinh) {
            UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamRequest inValue = new UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoNamRequestBody();
            inValue.Body.nam = nam;
            inValue.Body.idGiaDinh = idGiaDinh;
            return ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).thongKeThanhVienTheoNamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangResponse UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.thongKeThanhVienTheoThang(UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangRequest request) {
            return base.Channel.thongKeThanhVienTheoThang(request);
        }
        
        public string thongKeThanhVienTheoThang(string nam, string thang, int idGiaDinh) {
            UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangRequest inValue = new UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangRequestBody();
            inValue.Body.nam = nam;
            inValue.Body.thang = thang;
            inValue.Body.idGiaDinh = idGiaDinh;
            UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangResponse retVal = ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).thongKeThanhVienTheoThang(inValue);
            return retVal.Body.thongKeThanhVienTheoThangResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangResponse> UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.thongKeThanhVienTheoThangAsync(UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangRequest request) {
            return base.Channel.thongKeThanhVienTheoThangAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangResponse> thongKeThanhVienTheoThangAsync(string nam, string thang, int idGiaDinh) {
            UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangRequest inValue = new UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.thongKeThanhVienTheoThangRequestBody();
            inValue.Body.nam = nam;
            inValue.Body.thang = thang;
            inValue.Body.idGiaDinh = idGiaDinh;
            return ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).thongKeThanhVienTheoThangAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngDungDesktop.QuanLiThuChiService.timKiemResponse UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.timKiem(UngDungDesktop.QuanLiThuChiService.timKiemRequest request) {
            return base.Channel.timKiem(request);
        }
        
        public string timKiem(string chuoiXmlDuLieuTimKiem) {
            UngDungDesktop.QuanLiThuChiService.timKiemRequest inValue = new UngDungDesktop.QuanLiThuChiService.timKiemRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.timKiemRequestBody();
            inValue.Body.chuoiXmlDuLieuTimKiem = chuoiXmlDuLieuTimKiem;
            UngDungDesktop.QuanLiThuChiService.timKiemResponse retVal = ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).timKiem(inValue);
            return retVal.Body.timKiemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.timKiemResponse> UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.timKiemAsync(UngDungDesktop.QuanLiThuChiService.timKiemRequest request) {
            return base.Channel.timKiemAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.timKiemResponse> timKiemAsync(string chuoiXmlDuLieuTimKiem) {
            UngDungDesktop.QuanLiThuChiService.timKiemRequest inValue = new UngDungDesktop.QuanLiThuChiService.timKiemRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.timKiemRequestBody();
            inValue.Body.chuoiXmlDuLieuTimKiem = chuoiXmlDuLieuTimKiem;
            return ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).timKiemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UngDungDesktop.QuanLiThuChiService.layIdThuChiChungResponse UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.layIdThuChiChung(UngDungDesktop.QuanLiThuChiService.layIdThuChiChungRequest request) {
            return base.Channel.layIdThuChiChung(request);
        }
        
        public string layIdThuChiChung(int idGiaDinh) {
            UngDungDesktop.QuanLiThuChiService.layIdThuChiChungRequest inValue = new UngDungDesktop.QuanLiThuChiService.layIdThuChiChungRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.layIdThuChiChungRequestBody();
            inValue.Body.idGiaDinh = idGiaDinh;
            UngDungDesktop.QuanLiThuChiService.layIdThuChiChungResponse retVal = ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).layIdThuChiChung(inValue);
            return retVal.Body.layIdThuChiChungResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.layIdThuChiChungResponse> UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap.layIdThuChiChungAsync(UngDungDesktop.QuanLiThuChiService.layIdThuChiChungRequest request) {
            return base.Channel.layIdThuChiChungAsync(request);
        }
        
        public System.Threading.Tasks.Task<UngDungDesktop.QuanLiThuChiService.layIdThuChiChungResponse> layIdThuChiChungAsync(int idGiaDinh) {
            UngDungDesktop.QuanLiThuChiService.layIdThuChiChungRequest inValue = new UngDungDesktop.QuanLiThuChiService.layIdThuChiChungRequest();
            inValue.Body = new UngDungDesktop.QuanLiThuChiService.layIdThuChiChungRequestBody();
            inValue.Body.idGiaDinh = idGiaDinh;
            return ((UngDungDesktop.QuanLiThuChiService.XuLiDichVuSoap)(this)).layIdThuChiChungAsync(inValue);
        }
    }
}
